### ISSUE TITLE
After installation by composer, I get an error when use Setup:Upgrade

### ISSUE THREAD

**Issue by othonlima** [i9-digital/magento2-street-labels#1]
Autoload error: Module 'I9_StreetLabel' from '/var/www/html/magento/app/code/I9/StreetLabel' has been already defined in '/var/www/html/magento/vendor/i9/streetlabel'.root@bdfbfe8d2dc4:/var/www/html/magento# p

I removed the code\I9 directory, but the application is looping after change Custumer Configuration

**Comment by ianitsky** [comment]
hanks for the feedback.

Execute the commands to resolve:

composer remove i9/streetlabel
composer require i9/streetlabel:0.0.2
