### ISSUE TITLE
Sugestão: Adicionar também no perfil do usuário

### ISSUE THREAD

**Issue by LimaJonas** [i9-digital/magento2-street-labels#3]
Eae tudo bom?

Cara, você resolveu meus problemas, estava tentando adicionar labels no endereço no checkout e seu módulo me ajudou. 

Mas como sugestão, seria interessante colocar também essas labels no perfil do usuário (/customer/address/edit/id/0/).

Agradeço pelo módulo e desejo sucesso, flw

**Comment by ianitsky** [comment]
Estamos aceitando PRs =)
